defaults:
  - _self_
  - model: parseq
  - charset: 62_mixed-case
  - dataset: words_v4

model:
  _convert_: all
  img_size: [ 77, 154 ]  # [ height, width ]
  max_label_length: 30
  # The ordering in charset_train matters. It determines the token IDs assigned to each character.
  charset_train: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  # For charset_test, ordering doesn't matter.
  charset_test: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  batch_size: 128
  weight_decay: 0.0
  warmup_pct: 0.075  # equivalent to 1.5 epochs of warm up

data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: /kaggle/input/pr-ocr-lmdb-words-v4/
  train_dir: ???
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 4

trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 64
  check_val_every_n_epoch: 3
  #max_steps: 169680  # 20 epochs x 8484 steps (for batch size = 384, real data)
  max_epochs: 200
  gradient_clip_val: 20
  accelerator: gpu
  devices: 2

ckpt_path: null
pretrained: null

hydra:
  output_subdir: config
  run:
    dir: outputs/${model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: multirun/${model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
